name: On Push
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Do stuff
      id: stuff
      run: |
        echo "OUTPUT='true'" >> "$GITHUB_OUTPUT"
    outputs:
      OUTPUT: ${{ steps.stuff.outputs.OUTPUT }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.build.outputs.OUTPUT == 'true' }}
    steps: 
    - name: Release
      uses: ./.github/workflows/release.yml
